export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_INCREMENT_IF_ODD = 'COUNTER_INCREMENT_IF_ODD';
export const COUNTER_INCREMENT_ASYNC = 'COUNTER_INCREMENT_ASYNC';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_DECREMENT_ASYNC = 'COUNTER_DECREMENT_ASYNC';
